// env-config.js
window.env = {
    VITE_APP_VERSION: '__VITE_APP_VERSION__',
    GENERATE_SOURCEMAP: '__GENERATE_SOURCEMAP__',
    PUBLIC_URL: '__PUBLIC_URL__',
    VITE_APP_BASE_NAME: '__VITE_APP_BASE_NAME__',
    VITE_APP_API_URL: '__VITE_APP_API_URL__',
    VITE_APP_AWS_POOL_ID: '__VITE_APP_AWS_POOL_ID__',
    VITE_APP_AWS_APP_CLIENT_ID: '__VITE_APP_AWS_APP_CLIENT_ID__',
    VITE_STRIPE_PUBLISHABLE_KEY: '__VITE_STRIPE_PUBLISHABLE_KEY__'
  };
  